[alpine]

[debian]
debian13 ansible_host=192.168.100.198 ansible_user=ansible
debian13-D ansible_host=192.168.100.178 ansible_user=ansible
proxmox ansible_host=192.168.100.100 ansible_user=ansible
debian13-k8s ansible_host=192.168.100.246 ansible_user=ansible

[rhel]
rh7el ansible_host=192.168.100.172 ansible_user=ansible
rh8el ansible_host=192.168.100.239 ansible_user=ansible
rhel9 ansible_host=192.168.100.36 ansible_user=ansible
rhel10 ansible_host=192.168.100.101 ansible_user=ansible
rhel9-AM ansible_host=192.168.100.231 ansible_user=ansible
rhel8-AS ansible_host=192.168.100.147 ansible_user=ansible
rhel9-AS ansible_host=192.168.100.20 ansible_user=ansible
wazuh ansible_host=192.168.100.79 ansible_user=ansible

[ubuntu]
Ubuntu_MC ansible_host=192.168.100.160 ansible_user=ansible
Ubuntu_VM ansible_host=192.168.100.154 ansible_user=ansible
Lubuntu_AFG ansible_host=192.168.100.82 ansible_user=ansible
