[alpine]

[debian]
debian13 ansible_host=192.168.100.198 ansible_user=ansible
debian ansible_host=192.168.100.178 ansible_user=ansible

[rhel]
rh7 ansible_host=192.168.100.172 ansible_user=ansible
rh8 ansible_host=192.168.100.239 ansible_user=ansible
rh9 ansible_host=192.168.100.36 ansible_user=ansible
rh10 ansible_host=192.168.100.101 ansible_user=ansible
rhel8 ansible_host=192.168.100.147 ansible_user=ansible
rhel9 ansible_host=192.168.100.20 ansible_user=ansible
rhel9-A ansible_host=192.168.100.231 ansible_user=ansible

[ubuntu]
Ubuntu_MC ansible_host=192.168.100.160 ansible_user=ansible
Ubuntu_VM ansible_host=192.168.100.145 ansible_user=ansible
